{application,issues,
             [{registered,[]},
              {description,"issues"},
              {vsn,"0.0.1"},
              {modules,['Elixir.FibScheduler','Elixir.FibSolver',
                        'Elixir.Issues','Elixir.Issues.CLI',
                        'Elixir.Issues.GithubIssues',
                        'Elixir.Issues.TableFormatter','Elixir.Spawn']},
              {applications,[kernel,stdlib,elixir,logger,httpoison]}]}.